Repository deeqakkk/Journey-with-js, pull requests merged in 2022-10, with the labels that each got.

#7 Google clone
  google_clone/index.html
  google_clone/script.js
  google_clone/style.css
Labels: good first issue, Hacktoberfest

#58 Update Live-here file as per the project submission
  Live-here.md
Labels: documentation, Hacktoberfest

#66 Added Ball Fall game
  21-BallFall-game/index.html
  21-BallFall-game/script.js
  21-BallFall-game/style.css
Labels: Hacktoberfest, changes-requested

#67 21-JokeMe Added
  21-JokeMe/index.html
  21-JokeMe/script.js
Labels: Hacktoberfest, Un-necessary-files

#73 25-Blog Page
  25-Blog Page/blog.html
  25-Blog Page/img/challenges.jpg
  25-Blog Page/img/laura-jones.jpg
  25-Blog Page/img/post-img.jpg
  25-Blog Page/img/related-1.jpg
  25-Blog Page/img/related-2.jpg
  25-Blog Page/img/related-3.jpg
  25-Blog Page/index.html
  25-Blog Page/style.css
Labels: good first issue, Hacktoberfest

#76 Typing Test
  27-Typing-Test/index.html
  27-Typing-Test/script.js
  27-Typing-Test/style.css
Labels: good-first-issues, Hacktoberfest
